# Sitio de ejemplo con /.env expuesto a propósito
server {
    listen 443 ssl;
    server_name target-endpoint;

    ssl_certificate     /etc/nginx/ssl/target.crt;
    ssl_certificate_key /etc/nginx/ssl/target.key;

    # El access log va por syslog con tag "nginx"
    access_log syslog:server=unix:/dev/log,tag=nginx,severity=info,nohostname combined;

    root /var/www/vuln-web;
    index index.html;

    location = /.env {
        default_type text/plain;
    }
}
